# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: |
          git pull origin main
          ./gradlew build -x test
          java -jar ./build/libs/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
      - name: Test
        run: |
          run: java -jar ./build/libs/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar stop
          ./gradlew test -i
      #- name: Validate
      #- name: Deploy
